// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhyXPDXaEOMyCWyQOY-gNUF2j8znZzpqA',
    appId: '1:98570070312:web:4968a4b792bcb3706e081d',
    messagingSenderId: '98570070312',
    projectId: 'bookstore-b232d',
    authDomain: 'bookstore-b232d.firebaseapp.com',
    storageBucket: 'bookstore-b232d.firebasestorage.app',
    measurementId: 'G-0YCBYQ9895',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5YO9Xmb7JkiYCvxt-BWpsn9x4y66FDoY',
    appId: '1:98570070312:android:5d4faf46378916c36e081d',
    messagingSenderId: '98570070312',
    projectId: 'bookstore-b232d',
    storageBucket: 'bookstore-b232d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLKM4YdSymj59MTsHLPAqujWc121xfaqE',
    appId: '1:98570070312:ios:4b85f5ffc3360d576e081d',
    messagingSenderId: '98570070312',
    projectId: 'bookstore-b232d',
    storageBucket: 'bookstore-b232d.firebasestorage.app',
    iosBundleId: 'com.example.bookstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLKM4YdSymj59MTsHLPAqujWc121xfaqE',
    appId: '1:98570070312:ios:4b85f5ffc3360d576e081d',
    messagingSenderId: '98570070312',
    projectId: 'bookstore-b232d',
    storageBucket: 'bookstore-b232d.firebasestorage.app',
    iosBundleId: 'com.example.bookstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhyXPDXaEOMyCWyQOY-gNUF2j8znZzpqA',
    appId: '1:98570070312:web:a0e719d5a0582bb16e081d',
    messagingSenderId: '98570070312',
    projectId: 'bookstore-b232d',
    authDomain: 'bookstore-b232d.firebaseapp.com',
    storageBucket: 'bookstore-b232d.firebasestorage.app',
    measurementId: 'G-R1NMBLQR45',
  );
}
